[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bridge = "Dqm2bYqHFUBEK1FYu2PB5YbP4Y66E7RtY9rUnB6sCfeG"
message = "62StCRGCjwWqhXzrUhjtv7gDjy6ePjFCMBH72Ket49w8"
root = "227VueSAxiT1kEnESEcqpX2em9p2D1WA5GG1MU9vLz6Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
bridge = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/bridge.ts"
message = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/message.ts"
root = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/root.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
view = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/view.ts"
sub = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/sub.ts"
